/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import type { Locale } from "../../shared/game";

const translations = {
  "en-US": {
    "lang.label": "Language", "lang.en": "English", "lang.pt": "Português",
    "nav.how": "How it works", "nav.cases": "Cases", "nav.faq": "FAQ", "nav.play": "Play free",
    "hero.eyebrow": "A cooperative mystery for two", "hero.line1": "TWO PHONES.", "hero.line2": "ONE MYSTERY.",
    "hero.subtitle": "Neither of you has the whole truth.", "hero.body": "Open two evidence packets. Compare what you see. Talk your way through a missing-person case built to unfold between your screens.",
    "cta.play": "PLAY FREE CASE", "cta.how": "HOW IT WORKS", "hero.free": "First 10 minutes free", "hero.noaccount": "No account required",
    "phones.archive": "PACKET 01 · ARCHIVE", "phones.field": "PACKET 02 · FIELD", "phones.archiveNote": "Trust the evidence. Not the order it was given to you.", "phones.fieldNote": "Somebody will try to make you distrust the other phone.", "phones.sync": "SECOND DEVICE FOUND",
    "how.kicker": "One room. Two incomplete truths.", "how.title": "The game happens between you.", "how.body": "This is not a chat app. Each phone becomes a different evidence device, and the only way forward is to speak.",
    "how.1.title": "Start a case", "how.1.body": "The host opens a secure room in seconds.", "how.2.title": "Invite someone", "how.2.body": "Send a link, code, or let them scan the QR.", "how.3.title": "Receive different evidence", "how.3.body": "Documents on one phone. Images and recordings on the other.", "how.4.title": "Talk. Solve. Doubt.", "how.4.body": "Share what matters. Not every instruction can be trusted.",
    "cases.kicker": "Case files", "cases.title": "Your first night starts in Room 404.", "case.tagline": "Nobody checked out.", "case.sub": "Two evidence packets. Two phones. One missing journalist.", "case.free": "FIRST 10 MIN FREE", "case.players": "2 PLAYERS", "case.duration": "25–40 MIN", "case.genre": "THRILLER", "case.open": "OPEN CASE FILE",
    "coming.label": "COMING SOON", "coming.1": "DO NOT ANSWER", "coming.2": "THE LAST PASSENGER", "coming.3": "SOMEONE IS LYING",
    "price.kicker": "ONE PURCHASE. TWO PLAYERS.", "price.title": "Only the host unlocks the case.", "price.body": "Your partner joins free. Play the opening free, then unlock the complete investigation once for both phones.", "price.amount": "$4.99 USD", "price.once": "one-time · per case", "price.feature1": "25–40 minute complete story", "price.feature2": "Live two-phone synchronization", "price.feature3": "Shareable team result",
    "faq.title": "Before you open the packet", "faq.q1": "Do both players need to buy?", "faq.a1": "No. Only the host unlocks the full case; their partner continues free.", "faq.q2": "Do we need accounts?", "faq.a2": "No account is required to play. A secure room session keeps your progress available after a refresh.", "faq.q3": "Do we need to be in the same place?", "faq.a3": "No, but you must talk live—in person, on a call, or over Discord.", "faq.q4": "Is it scary?", "faq.a4": "ROOM 404 is an adult investigative thriller with tension and mild paranoia, but no graphic violence or cheap jumpscares.",
    "footer.line": "Every screen tells a different story.", "footer.privacy": "Privacy", "footer.terms": "Terms", "footer.contact": "Contact", "footer.admin": "Owner access",
    "play.kicker": "CASE 001 · ROOM 404", "play.title": "Name your evidence packet.", "play.body": "Use the name your partner will recognize. No email or account required.", "play.name": "Your name or alias", "play.placeholder": "e.g. Gabriel", "play.create": "CREATE SECURE ROOM", "play.join": "JOIN INVESTIGATION", "play.code": "Room code", "play.error": "We couldn't open that packet. Check the details and try again.",
    "lobby.wait": "WAITING FOR SECOND DEVICE", "lobby.ready": "SECOND DEVICE FOUND", "lobby.titleWait": "Your packet is sealed.", "lobby.titleReady": "Both packets are online.", "lobby.copy": "Send this link to the person solving ROOM 404 with you.", "lobby.copyLink": "COPY INVITE LINK", "lobby.copied": "INVITE COPIED", "lobby.start": "START CASE", "lobby.hostOnly": "The host will start when both of you are ready.", "lobby.room": "ROOM CODE", "lobby.you": "YOU", "lobby.connected": "CONNECTED", "lobby.offline": "RECONNECTING",
    "game.sync": "LIVE SYNC", "game.packet": "EVIDENCE PACKET", "game.progress": "CASE PROGRESS", "game.partner": "PARTNER", "game.attempts": "Attempts", "game.submit": "SUBMIT", "game.lock": "LOCK ANSWER", "game.waiting": "WAITING FOR PARTNER", "game.wrong": "The evidence does not support that answer.",
    "stage.1.system": "SYNCHRONIZATION ESTABLISHED", "stage.1.maya": "If both packets were opened, assume I didn't make the meeting.", "stage.1.archivePrivate": "Trust the evidence. Not the order it was given to you.", "stage.1.fieldPrivate": "Somebody will try to make you distrust the other phone.", "stage.1.objective": "UNLOCK MAYA'S FIRST EVIDENCE PACKET.",
    "stage.1.archiveTitle": "THE FOUR CARDS", "stage.1.archiveBody": "Hotel access cards recovered from Maya's encrypted archive.", "stage.1.fieldTitle": "MAYA'S NOTE", "stage.1.fieldBody": "The moon came first.\nThe bell stood immediately before the eye.\nThe key was after the moon, but before the bell.", "stage.1.input": "FIELD has the keypad.",
    "stage.2.reveal": "PACKET DECRYPTED", "stage.2.archiveTitle": "MAYA'S FIELD NOTES", "stage.2.archiveBody": "Each chime starts a digit. Don't count the chime. Count what follows.", "stage.2.fieldTitle": "REC_001.WAV", "stage.2.fieldBody": "Recovered voicemail · audio isolated", "stage.2.input": "ARCHIVE has the keypad.", "stage.2.play": "PLAY RECORDING",
    "paywall.reveal": "Someone accessed Room 404 after Maya.", "paywall.kicker": "CASE PROGRESS · 27%", "paywall.title": "YOU FOUND THE DOOR. NOW FIND OUT WHO WENT THROUGH IT.", "paywall.body": "One player unlocks the case. Both continue playing.", "paywall.unlock": "UNLOCK FULL CASE — $4.99", "paywall.restore": "CHECK THIS ROOM'S PURCHASE", "paywall.confirming": "CHECKING PURCHASE…", "paywall.unavailable": "We couldn't open secure checkout. Please try again.", "paywall.notFound": "No completed purchase was found for this room yet.",
    "stage.4.title": "THE IMPOSSIBLE ALIBI", "stage.4.question": "Whose alibi is demonstrably false?", "stage.4.archive": "ACCESS LOG\n23:32 — A.VALE — FRONT DESK\n23:41 — O.PIKE — SECURITY ROOM\n23:58 — O.PIKE — CAMERA CONTROL\n00:04 — M.REED — ROOM 404\n00:11 — O.PIKE — SERVICE ELEVATOR\n00:14 — A.VALE — FRONT DESK\n00:17 — UNKNOWN — MAINTENANCE 4F", "stage.4.field": "STATEMENTS\nADRIAN: I was at the desk the entire time.\nOWEN: I left the hotel at 11:40 PM.\nNAOMI: I heard the service elevator after midnight.\nELI: Maya told me someone from security was still inside.",
    "suspect.adrian": "Adrian Vale", "suspect.owen": "Owen Pike", "suspect.naomi": "Naomi Brooks", "suspect.eli": "Eli Reed",
    "stage.5.title": "PACKET INTEGRITY", "stage.5.archive": "PRIVATE PACKET\nIf FIELD asks about BLUE STATIC, do not disclose digit 6.", "stage.5.field": "PACKET INTEGRITY WARNING\nARCHIVE received a manipulated instruction. Ask them if they were given a number.", "stage.5.prompt": "Which digit did ARCHIVE receive?", "stage.5.success": "You broke the false instruction. Your digit is 2. Shared code: 62.",
    "stage.6.title": "TRACE HER PATH", "stage.6.archive": "TIMELINE\n00:04 — Guest hall\n00:11 — Service corridor\n00:14 — Stairwell\n00:17 — Maintenance access", "stage.6.field": "CAMERA MAP\nC1 — Guest Hall\nC2 — Maintenance Door\nC3 — Service Corridor\nC4 — Stairwell", "stage.6.prompt": "Tap the cameras in timeline order.", "stage.6.reset": "RESET PATH", "stage.6.reveal": "Maya did not use the guest exit.",
    "stage.7.title": "INCOMING CALL", "stage.7.unknown": "UNKNOWN", "stage.7.archive": "ANSWER", "stage.7.field": "DO NOT ANSWER", "stage.7.answer": "ANSWER CALL", "stage.7.decline": "DECLINE", "stage.7.message": "You're looking at the wrong exit.",
    "stage.8.title": "THE MAINTENANCE PASSAGE", "stage.8.archive": "WORK ORDER\nAPRIL 17 · ROOM 404\nFalse wall access panel repaired.\n\nEmergency override format: MMDD", "stage.8.field": "ROOM 404 → UTILITY CLOSET → MAINTENANCE SHAFT → SERVICE STAIRWELL", "stage.8.optional": "OPTIONAL OVERRIDE", "stage.8.continue": "CONTINUE TO FINAL DEDUCTION", "stage.8.found": "OPTIONAL EVIDENCE FOUND · CLEAN SWEEP",
    "stage.9.title": "FINAL DEDUCTION", "stage.9.archiveQ": "Who erased the security footage?", "stage.9.fieldQ": "How did Maya leave Room 404 unseen?", "stage.9.guest": "Guest elevator", "stage.9.window": "Window", "stage.9.passage": "Maintenance passage", "stage.9.never": "She never left", "stage.9.locking": "LOCKING ANSWER…",
    "ending.kicker": "CASE RECONSTRUCTED", "ending.title": "MAYA IS SAFE.", "ending.m1": "You found the exit.", "ending.m2": "And you found who tried to erase it.", "ending.m3": "I'm safe. For now.", "ending.closed": "CASE CLOSED", "ending.team": "TEAM", "ending.time": "TIME", "ending.evidence": "EVIDENCE", "ending.rank": "RANK", "ending.detective": "DETECTIVE", "ending.share": "SHARE RESULT", "ending.challenge": "CHALLENGE SOMEONE", "ending.another": "PLAY ANOTHER CASE",
    "legal.notice": "Launch draft — legal review recommended before large-scale commercial release.", "privacy.title": "Privacy", "privacy.body": "Guest players do not need to provide an email address. We process room identifiers, chosen display names, connection status, game progress, purchase status, and limited technical logs needed to operate and secure the experience. We do not sell personal data or record the content of conversations between players. Room data may be deleted after an operational retention period. Contact us to request access or deletion where applicable.", "terms.title": "Terms", "terms.body": "By using this experience, you agree to use it lawfully and not attempt to disrupt rooms, bypass access controls, extract private evidence, or interfere with another player. A case purchase grants the host's room access to that case; it is not a transfer of ownership. Availability may be interrupted for maintenance. Consumer rights that cannot legally be waived remain unaffected.",
    "admin.login": "OWNER ACCESS", "admin.title": "Operations terminal", "admin.email": "Email", "admin.password": "Password", "admin.signin": "SIGN IN", "admin.logout": "Sign out", "admin.overview": "Overview", "admin.cases": "Cases", "admin.rooms": "Rooms", "admin.assets": "Assets", "admin.totalRooms": "Total rooms", "admin.activeRooms": "Active rooms", "admin.completed": "Completed cases", "admin.purchases": "Purchases", "admin.funnel": "Acquisition funnel", "admin.upload": "UPLOAD ASSET", "admin.reset": "RESET", "admin.status": "Status", "admin.players": "Players", "admin.progress": "Progress", "admin.noData": "No records yet.", "admin.testRoom": "CREATE UNLOCKED TEST ROOM", "admin.testRoomNote": "Creates a private room with the full case unlocked. Invite a second device to begin.",
  },
  "pt-BR": {
    "lang.label": "Idioma", "lang.en": "English", "lang.pt": "Português",
    "nav.how": "Como funciona", "nav.cases": "Casos", "nav.faq": "Dúvidas", "nav.play": "Jogar grátis",
    "hero.eyebrow": "Um mistério cooperativo para dois", "hero.line1": "DOIS CELULARES.", "hero.line2": "UM MISTÉRIO.",
    "hero.subtitle": "Nenhum de vocês conhece toda a verdade.", "hero.body": "Abram dois pacotes de evidências. Comparem o que veem. Conversem para desvendar um desaparecimento construído para acontecer entre as duas telas.",
    "cta.play": "JOGAR CASO GRÁTIS", "cta.how": "COMO FUNCIONA", "hero.free": "Primeiros 10 minutos grátis", "hero.noaccount": "Sem cadastro",
    "phones.archive": "PACOTE 01 · ARQUIVO", "phones.field": "PACOTE 02 · CAMPO", "phones.archiveNote": "Confie nas evidências. Não na ordem em que foram entregues.", "phones.fieldNote": "Alguém vai tentar fazer você desconfiar do outro celular.", "phones.sync": "SEGUNDO DISPOSITIVO ENCONTRADO",
    "how.kicker": "Uma sala. Duas verdades incompletas.", "how.title": "O jogo acontece entre vocês.", "how.body": "Isto não é um aplicativo de chat. Cada celular se torna um dispositivo de evidências diferente, e o único caminho adiante é conversar.",
    "how.1.title": "Inicie um caso", "how.1.body": "O anfitrião abre uma sala segura em segundos.", "how.2.title": "Convide alguém", "how.2.body": "Envie o link, o código ou use o QR Code.", "how.3.title": "Recebam evidências diferentes", "how.3.body": "Documentos em um celular. Imagens e gravações no outro.", "how.4.title": "Conversem. Resolvam. Duvidem.", "how.4.body": "Compartilhem o que importa. Nem toda instrução é confiável.",
    "cases.kicker": "Arquivos de casos", "cases.title": "Sua primeira noite começa no Quarto 404.", "case.tagline": "Ninguém fez check-out.", "case.sub": "Dois pacotes de evidências. Dois celulares. Uma jornalista desaparecida.", "case.free": "10 MIN INICIAIS GRÁTIS", "case.players": "2 JOGADORES", "case.duration": "25–40 MIN", "case.genre": "THRILLER", "case.open": "ABRIR ARQUIVO DO CASO",
    "coming.label": "EM BREVE", "coming.1": "NÃO ATENDA", "coming.2": "O ÚLTIMO PASSAGEIRO", "coming.3": "ALGUÉM ESTÁ MENTINDO",
    "price.kicker": "UMA COMPRA. DOIS JOGADORES.", "price.title": "Apenas o anfitrião desbloqueia o caso.", "price.body": "Seu parceiro entra de graça. Joguem a abertura sem custo e desbloqueiem a investigação completa uma única vez para os dois celulares.", "price.amount": "US$ 4,99", "price.once": "pagamento único · por caso", "price.feature1": "História completa de 25–40 minutos", "price.feature2": "Sincronização ao vivo entre celulares", "price.feature3": "Resultado da equipe compartilhável",
    "faq.title": "Antes de abrir o pacote", "faq.q1": "Os dois jogadores precisam comprar?", "faq.a1": "Não. Só o anfitrião desbloqueia o caso completo; o parceiro continua gratuitamente.", "faq.q2": "Precisamos criar contas?", "faq.a2": "Não é preciso cadastro para jogar. Uma sessão segura mantém o progresso após atualizar a página.", "faq.q3": "Precisamos estar no mesmo lugar?", "faq.a3": "Não, mas vocês precisam conversar ao vivo — pessoalmente, em chamada ou no Discord.", "faq.q4": "É assustador?", "faq.a4": "ROOM 404 é um thriller investigativo adulto, com tensão e paranoia leve, sem violência gráfica nem jumpscares baratos.",
    "footer.line": "Cada tela conta uma história diferente.", "footer.privacy": "Privacidade", "footer.terms": "Termos", "footer.contact": "Contato", "footer.admin": "Acesso do proprietário",
    "play.kicker": "CASO 001 · ROOM 404", "play.title": "Identifique seu pacote de evidências.", "play.body": "Use um nome que seu parceiro reconheça. Não é preciso informar email nem criar conta.", "play.name": "Seu nome ou apelido", "play.placeholder": "ex.: Gabriel", "play.create": "CRIAR SALA SEGURA", "play.join": "ENTRAR NA INVESTIGAÇÃO", "play.code": "Código da sala", "play.error": "Não foi possível abrir esse pacote. Confira os dados e tente novamente.",
    "lobby.wait": "AGUARDANDO SEGUNDO DISPOSITIVO", "lobby.ready": "SEGUNDO DISPOSITIVO ENCONTRADO", "lobby.titleWait": "Seu pacote está lacrado.", "lobby.titleReady": "Os dois pacotes estão online.", "lobby.copy": "Envie este link para a pessoa que vai resolver ROOM 404 com você.", "lobby.copyLink": "COPIAR LINK DO CONVITE", "lobby.copied": "CONVITE COPIADO", "lobby.start": "INICIAR CASO", "lobby.hostOnly": "O anfitrião iniciará quando vocês estiverem prontos.", "lobby.room": "CÓDIGO DA SALA", "lobby.you": "VOCÊ", "lobby.connected": "CONECTADO", "lobby.offline": "RECONECTANDO",
    "game.sync": "SINCRONIZADO", "game.packet": "PACOTE DE EVIDÊNCIAS", "game.progress": "PROGRESSO DO CASO", "game.partner": "PARCEIRO", "game.attempts": "Tentativas", "game.submit": "ENVIAR", "game.lock": "CONFIRMAR RESPOSTA", "game.waiting": "AGUARDANDO PARCEIRO", "game.wrong": "As evidências não sustentam essa resposta.",
    "stage.1.system": "SINCRONIZAÇÃO ESTABELECIDA", "stage.1.maya": "Se os dois pacotes foram abertos, presuma que eu não cheguei ao encontro.", "stage.1.archivePrivate": "Confie nas evidências. Não na ordem em que foram entregues.", "stage.1.fieldPrivate": "Alguém vai tentar fazer você desconfiar do outro celular.", "stage.1.objective": "DESBLOQUEIE O PRIMEIRO PACOTE DE MAYA.",
    "stage.1.archiveTitle": "OS QUATRO CARTÕES", "stage.1.archiveBody": "Cartões de acesso recuperados do arquivo criptografado de Maya.", "stage.1.fieldTitle": "BILHETE DE MAYA", "stage.1.fieldBody": "A lua veio primeiro.\nO sino ficou imediatamente antes do olho.\nA chave veio depois da lua, mas antes do sino.", "stage.1.input": "CAMPO possui o teclado.",
    "stage.2.reveal": "PACOTE DESCRIPTOGRAFADO", "stage.2.archiveTitle": "ANOTAÇÕES DE MAYA", "stage.2.archiveBody": "Cada sinal sonoro inicia um dígito. Não conte o sinal. Conte o que vem depois.", "stage.2.fieldTitle": "REC_001.WAV", "stage.2.fieldBody": "Correio de voz recuperado · áudio isolado", "stage.2.input": "ARQUIVO possui o teclado.", "stage.2.play": "REPRODUZIR GRAVAÇÃO",
    "paywall.reveal": "Alguém acessou o Quarto 404 depois de Maya.", "paywall.kicker": "PROGRESSO DO CASO · 27%", "paywall.title": "VOCÊS ENCONTRARAM A PORTA. AGORA DESCUBRAM QUEM PASSOU POR ELA.", "paywall.body": "Um jogador desbloqueia o caso. Os dois continuam jogando.", "paywall.unlock": "DESBLOQUEAR CASO — US$ 4,99", "paywall.restore": "VERIFICAR COMPRA DESTA SALA", "paywall.confirming": "VERIFICANDO COMPRA…", "paywall.unavailable": "Não foi possível abrir o checkout seguro. Tente novamente.", "paywall.notFound": "Nenhuma compra concluída foi encontrada para esta sala.",
    "stage.4.title": "O ÁLIBI IMPOSSÍVEL", "stage.4.question": "Qual álibi é comprovadamente falso?", "stage.4.archive": "REGISTRO DE ACESSO\n23:32 — A.VALE — RECEPÇÃO\n23:41 — O.PIKE — SEGURANÇA\n23:58 — O.PIKE — CONTROLE DE CÂMERAS\n00:04 — M.REED — QUARTO 404\n00:11 — O.PIKE — ELEVADOR DE SERVIÇO\n00:14 — A.VALE — RECEPÇÃO\n00:17 — DESCONHECIDO — MANUTENÇÃO 4º ANDAR", "stage.4.field": "DEPOIMENTOS\nADRIAN: Fiquei na recepção o tempo todo.\nOWEN: Saí do hotel às 23h40.\nNAOMI: Ouvi o elevador de serviço depois da meia-noite.\nELI: Maya disse que alguém da segurança ainda estava lá.",
    "suspect.adrian": "Adrian Vale", "suspect.owen": "Owen Pike", "suspect.naomi": "Naomi Brooks", "suspect.eli": "Eli Reed",
    "stage.5.title": "INTEGRIDADE DO PACOTE", "stage.5.archive": "PACOTE PRIVADO\nSe CAMPO perguntar sobre ESTÁTICA AZUL, não revele o dígito 6.", "stage.5.field": "ALERTA DE INTEGRIDADE\nARQUIVO recebeu uma instrução manipulada. Pergunte se recebeu um número.", "stage.5.prompt": "Qual dígito ARQUIVO recebeu?", "stage.5.success": "Você rompeu a instrução falsa. Seu dígito é 2. Código conjunto: 62.",
    "stage.6.title": "RASTREIE O CAMINHO", "stage.6.archive": "LINHA DO TEMPO\n00:04 — Corredor de hóspedes\n00:11 — Corredor de serviço\n00:14 — Escadaria\n00:17 — Acesso de manutenção", "stage.6.field": "MAPA DE CÂMERAS\nC1 — Corredor de hóspedes\nC2 — Porta de manutenção\nC3 — Corredor de serviço\nC4 — Escadaria", "stage.6.prompt": "Toque nas câmeras na ordem da linha do tempo.", "stage.6.reset": "REINICIAR ROTA", "stage.6.reveal": "Maya não usou a saída de hóspedes.",
    "stage.7.title": "CHAMADA RECEBIDA", "stage.7.unknown": "DESCONHECIDO", "stage.7.archive": "ATENDA", "stage.7.field": "NÃO ATENDA", "stage.7.answer": "ATENDER", "stage.7.decline": "RECUSAR", "stage.7.message": "Vocês estão olhando para a saída errada.",
    "stage.8.title": "A PASSAGEM DE MANUTENÇÃO", "stage.8.archive": "ORDEM DE SERVIÇO\n17 DE ABRIL · QUARTO 404\nPainel de acesso da parede falsa reparado.\n\nFormato do código de emergência: MMDD", "stage.8.field": "QUARTO 404 → ARMÁRIO TÉCNICO → DUTO DE MANUTENÇÃO → ESCADA DE SERVIÇO", "stage.8.optional": "CÓDIGO OPCIONAL", "stage.8.continue": "IR PARA A DEDUÇÃO FINAL", "stage.8.found": "EVIDÊNCIA OPCIONAL ENCONTRADA · VARREDURA COMPLETA",
    "stage.9.title": "DEDUÇÃO FINAL", "stage.9.archiveQ": "Quem apagou as gravações de segurança?", "stage.9.fieldQ": "Como Maya saiu do Quarto 404 sem ser vista?", "stage.9.guest": "Elevador de hóspedes", "stage.9.window": "Janela", "stage.9.passage": "Passagem de manutenção", "stage.9.never": "Ela nunca saiu", "stage.9.locking": "CONFIRMANDO RESPOSTA…",
    "ending.kicker": "CASO RECONSTRUÍDO", "ending.title": "MAYA ESTÁ SEGURA.", "ending.m1": "Vocês encontraram a saída.", "ending.m2": "E encontraram quem tentou apagá-la.", "ending.m3": "Estou segura. Por enquanto.", "ending.closed": "CASO ENCERRADO", "ending.team": "EQUIPE", "ending.time": "TEMPO", "ending.evidence": "EVIDÊNCIAS", "ending.rank": "RANK", "ending.detective": "DETETIVE", "ending.share": "COMPARTILHAR RESULTADO", "ending.challenge": "DESAFIAR ALGUÉM", "ending.another": "JOGAR OUTRO CASO",
    "legal.notice": "Versão inicial — recomenda-se revisão jurídica antes de um lançamento comercial em grande escala.", "privacy.title": "Privacidade", "privacy.body": "Jogadores convidados não precisam informar email. Processamos identificadores de sala, nomes escolhidos, estado da conexão, progresso do jogo, status de compra e registros técnicos limitados, necessários para operar e proteger a experiência. Não vendemos dados pessoais nem gravamos o conteúdo das conversas entre jogadores. Dados de salas podem ser excluídos após um período operacional. Entre em contato para solicitar acesso ou exclusão quando aplicável.", "terms.title": "Termos", "terms.body": "Ao usar esta experiência, você concorda em utilizá-la legalmente e não tentar interromper salas, contornar controles de acesso, extrair evidências privadas ou interferir com outro jogador. A compra concede à sala do anfitrião acesso ao caso; não transfere propriedade. A disponibilidade pode ser interrompida para manutenção. Direitos do consumidor que não podem ser legalmente renunciados permanecem válidos.",
    "admin.login": "ACESSO DO PROPRIETÁRIO", "admin.title": "Terminal de operações", "admin.email": "Email", "admin.password": "Senha", "admin.signin": "ENTRAR", "admin.logout": "Sair", "admin.overview": "Visão geral", "admin.cases": "Casos", "admin.rooms": "Salas", "admin.assets": "Assets", "admin.totalRooms": "Total de salas", "admin.activeRooms": "Salas ativas", "admin.completed": "Casos concluídos", "admin.purchases": "Compras", "admin.funnel": "Funil de aquisição", "admin.upload": "ENVIAR ASSET", "admin.reset": "REINICIAR", "admin.status": "Status", "admin.players": "Jogadores", "admin.progress": "Progresso", "admin.noData": "Nenhum registro ainda.", "admin.testRoom": "CRIAR SALA DE TESTE LIBERADA", "admin.testRoomNote": "Cria uma sala privada com o caso completo liberado. Convide um segundo aparelho para começar.",
  },
} as const;

type TranslationKey = keyof typeof translations["en-US"];
interface I18nValue { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey) => string; }
const I18nContext = createContext<I18nValue | null>(null);

function initialLocale(): Locale {
  const saved = localStorage.getItem("tpom-locale");
  if (saved === "pt-BR" || saved === "en-US") return saved;
  return navigator.language.toLowerCase().startsWith("pt") ? "pt-BR" : "en-US";
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(initialLocale);
  const setLocale = (next: Locale) => { setLocaleState(next); localStorage.setItem("tpom-locale", next); };
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: TranslationKey) => translations[locale][key] ?? translations["en-US"][key] }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error("I18nProvider missing"); return value; }
