import { useCallback, useEffect, useMemo, useState } from "react";
import type { GameAction, PlayerRole, PublicRoomState } from "../../../shared/game";
import { LanguageSwitcher } from "../../components/LanguageSwitcher";
import { useI18n } from "../../i18n";

interface Props { state: PublicRoomState; send: (action: GameAction) => Promise<void>; error: string | null; }
const lines = (value: string) => value.split("\n").map((line, index) => <span key={`${line}-${index}`}>{line || <br />}</span>);

function Evidence({ eyebrow, title, children, className = "" }: { eyebrow: string; title: string; children: React.ReactNode; className?: string }) {
  return <article className={`evidence ${className}`}><div className="evidence-top"><span>{eyebrow}</span><i>● REC</i></div><h2>{title}</h2><div className="evidence-content">{children}</div><div className="evidence-footer"><span>HALCYON / EVIDENCE</span><span>AUTHENTICATED</span></div></article>;
}

function CodePad({ onSubmit, length = 4 }: { onSubmit: (value: string) => void; length?: number }) {
  const { t } = useI18n(); const [value, setValue] = useState("");
  const press = (digit: string) => setValue((current) => current.length < length ? current + digit : current);
  return <div className="codepad"><div className="code-display" aria-label="code">{Array.from({ length }, (_, index) => <span key={index}>{value[index] ?? "·"}</span>)}</div><div className="keys">{"123456789".split("").map((digit) => <button key={digit} onClick={() => press(digit)}>{digit}</button>)}<button onClick={() => setValue("")}>×</button><button onClick={() => press("0")}>0</button><button onClick={() => { if (value.length === length) onSubmit(value); }}>↵</button></div><button className="button button-primary full" disabled={value.length !== length} onClick={() => onSubmit(value)}>{t("game.submit")}</button></div>;
}

function StageOne({ role, send }: { role: PlayerRole; send: Props["send"] }) {
  const { t } = useI18n();
  return <div className="game-scene"><div className="scene-lead"><span>{t("stage.1.system")}</span><blockquote>“{t("stage.1.maya")}”<cite>— MAYA REED / SCHEDULED MESSAGE</cite></blockquote><p className="private-note">{role === "ARCHIVE" ? t("stage.1.archivePrivate") : t("stage.1.fieldPrivate")}</p></div>
    {role === "ARCHIVE" ? <Evidence eyebrow="ARCHIVE · DECRYPTED 12%" title={t("stage.1.archiveTitle")}><p>{t("stage.1.archiveBody")}</p><div className="hotel-cards"><div><i>☾</i><b>3</b><small>MOON</small></div><div><i>⚿</i><b>7</b><small>KEY</small></div><div><i>♢</i><b>1</b><small>BELL</small></div><div><i>◉</i><b>9</b><small>EYE</small></div></div><p className="handoff">{t("stage.1.input")}</p></Evidence> : <Evidence eyebrow="FIELD · IMAGE 001" title={t("stage.1.fieldTitle")} className="photo-evidence"><div className="door-shot" style={{backgroundImage:"url('/evidence/room-404-door.webp')"}}><span>404</span></div><p className="typed-note">{lines(t("stage.1.fieldBody"))}</p><CodePad onSubmit={(value) => send({ type: "SUBMIT_CODE", value })}/></Evidence>}
  </div>;
}

function StageTwo({ role, send }: { role: PlayerRole; send: Props["send"] }) {
  const { t } = useI18n();
  return <div className="game-scene"><div className="event-banner">✓ {t("stage.2.reveal")}</div>{role === "ARCHIVE" ? <Evidence eyebrow="ARCHIVE · TEXT FILE" title={t("stage.2.archiveTitle")}><p className="typed-note">{t("stage.2.archiveBody")}</p><CodePad onSubmit={(value) => send({ type: "SUBMIT_CODE", value })}/></Evidence> : <Evidence eyebrow="FIELD · AUDIO ONLY" title={t("stage.2.fieldTitle")}><div className="audio-file"><button onClick={(event) => { const audio = event.currentTarget.nextElementSibling as HTMLAudioElement; void audio.play(); }}>▶</button><audio src="/audio/rec-001.wav"/><div><b>{t("stage.2.play")}</b><span className="waveform">▁▂▅▃▁▁▆▂▁▁▅▃▅▁▁▂▆▂▁▁</span></div></div><p>{t("stage.2.fieldBody")}</p><p className="handoff">{t("stage.2.input")}</p></Evidence>}</div>;
}

function Paywall({ code, refresh }: { code: string; refresh: () => void }) {
  const { t } = useI18n(); const [loading, setLoading] = useState(false); const [error, setError] = useState<"checkout"|"restore"|null>(null);
  const checkout = async () => { setLoading(true); setError(null); const response = await fetch("/api/payments/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ roomCode: code }) }); const data = await response.json() as { unlocked?: boolean; url?: string }; if (data.unlocked) refresh(); else if (data.url) window.location.assign(data.url); else { setError("checkout"); setLoading(false); } };
  const restore = useCallback(async (quiet = false) => { if (!quiet) { setLoading(true); setError(null); } const response = await fetch(`/api/payments/status/${code}`, { credentials: "include" }); const data = await response.json() as { unlocked?: boolean }; if (data.unlocked) refresh(); else if (!quiet) { setError("restore"); setLoading(false); } }, [code, refresh]);
  useEffect(() => { if (new URLSearchParams(window.location.search).get("payment") !== "success") return; let attempts = 0; const timer = window.setInterval(() => { attempts += 1; void restore(true); if (attempts >= 20) window.clearInterval(timer); }, 1_500); void restore(true); return () => window.clearInterval(timer); }, [restore]);
  return <div className="paywall"><div className="paywall-image" style={{backgroundImage:"url('/evidence/cctv-fourth-floor.webp')"}}><span>CAM 4F-02</span></div><div className="paywall-copy"><p className="kicker">{t("paywall.kicker")}</p><p className="reveal">{t("paywall.reveal")}</p><h1>{t("paywall.title")}</h1><p>{t("paywall.body")}</p><button className="button button-primary full" onClick={checkout} disabled={loading}>{loading ? t("paywall.confirming") : t("paywall.unlock")}</button><button className="text-button" onClick={() => restore()} disabled={loading}>{t("paywall.restore")}</button>{error && <p className="form-error">{t(error==="restore"?"paywall.notFound":"paywall.unavailable")}</p>}</div></div>;
}

function StageFour({ role, send, waiting }: { role: PlayerRole; send: Props["send"]; waiting: boolean }) {
  const { t } = useI18n(); const [selected, setSelected] = useState(""); const suspects = [["ADRIAN_VALE","adrian"],["OWEN_PIKE","owen"],["NAOMI_BROOKS","naomi"],["ELI_REED","eli"]];
  return <div className="game-scene"><Evidence eyebrow={`${role} · CROSS REFERENCE`} title={t("stage.4.title")}><div className="document-text">{lines(role === "ARCHIVE" ? t("stage.4.archive") : t("stage.4.field"))}</div></Evidence><div className="decision"><h3>{t("stage.4.question")}</h3><div className="choice-grid">{suspects.map(([value,key]) => <button className={selected === value ? "selected" : ""} key={value} onClick={() => setSelected(value)}>{t(`suspect.${key}` as never)}</button>)}</div><button className="button button-primary full" disabled={!selected || waiting} onClick={() => send({type:"VOTE",value:selected})}>{waiting ? t("game.waiting") : t("game.lock")}</button></div></div>;
}

function StageFive({ role, send }: { role: PlayerRole; send: Props["send"] }) { const { t } = useI18n(); return <div className="game-scene paranoia"><Evidence eyebrow={`${role} · PRIVATE / DO NOT SHARE`} title={t("stage.5.title")}><div className="document-text">{lines(role === "ARCHIVE" ? t("stage.5.archive") : t("stage.5.field"))}</div>{role === "FIELD" ? <><p>{t("stage.5.prompt")}</p><CodePad length={1} onSubmit={(value) => send({type:"CONFIRM_DIGIT",value})}/></> : <div className="wait-signal"><span className="pulse"/>{t("game.waiting")}</div>}</Evidence></div>; }

function StageSix({ role, send }: { role: PlayerRole; send: Props["send"] }) {
  const { t } = useI18n(); const [path, setPath] = useState<string[]>([]);
  const add = (camera:string) => setPath((current) => current.includes(camera) ? current : [...current, camera]);
  return <div className="game-scene"><Evidence eyebrow={`${role} · CAMERA RECOVERY INDEX`} title={t("stage.6.title")}><div className="document-text">{lines(role === "ARCHIVE" ? t("stage.6.archive") : t("stage.6.field"))}</div>{role === "FIELD" ? <><div className="camera-map" style={{backgroundImage:"url('/evidence/cctv-fourth-floor.webp')"}}>{["C1","C2","C3","C4"].map((camera) => <button key={camera} onClick={() => add(camera)}><span>{camera}</span></button>)}</div><div className="path-sequence">{path.map((camera,index)=><span key={camera}>{index+1} · {camera}</span>)}</div><div className="inline-actions"><button className="text-button" onClick={() => setPath([])}>{t("stage.6.reset")}</button><button className="button button-primary" disabled={path.length !== 4} onClick={() => send({type:"TRACE_PATH",value:path})}>{t("game.submit")}</button></div></> : <div className="wait-signal"><span className="pulse"/>{t("game.waiting")}</div>}</Evidence></div>;
}

function StageSeven({ role, send }: { role: PlayerRole; send: Props["send"] }) { const { t } = useI18n(); return <div className="incoming-call"><div className="caller-orbit"><span>?</span></div><p>{t("stage.7.title")}</p><h1>{t("stage.7.unknown")}</h1><div className={role === "ARCHIVE" ? "call-order answer" : "call-order decline"}>{role === "ARCHIVE" ? t("stage.7.archive") : t("stage.7.field")}</div>{role === "ARCHIVE" ? <div className="call-actions"><button onClick={() => send({type:"CALL_DECISION",value:"DECLINED"})}>×<span>{t("stage.7.decline")}</span></button><button onClick={() => send({type:"CALL_DECISION",value:"ANSWERED"})}>⌕<span>{t("stage.7.answer")}</span></button></div> : <div className="wait-signal"><span className="pulse"/>{t("game.waiting")}</div>}</div>; }

function StageEight({ role, state, send }: { role: PlayerRole; state: PublicRoomState; send: Props["send"] }) { const { t } = useI18n(); return <div className="game-scene"><Evidence eyebrow={`${role} · RECOVERED ROUTE`} title={t("stage.8.title")}><div className="passage-photo" style={{backgroundImage:"url('/evidence/maintenance-passage.webp')"}}/><div className="document-text">{lines(role === "ARCHIVE" ? t("stage.8.archive") : t("stage.8.field"))}</div>{state.optionalEvidence ? <div className="event-banner">✓ {t("stage.8.found")}</div> : <><p className="kicker">{t("stage.8.optional")}</p><CodePad length={3} onSubmit={(value) => send({type:"OPTIONAL_CODE",value})}/></>}<button className="button button-ghost full" onClick={() => send({type:"CONTINUE"})}>{t("stage.8.continue")}</button></Evidence></div>; }

function StageNine({ role, waiting, send }: { role: PlayerRole; waiting: boolean; send: Props["send"] }) { const { t } = useI18n(); const [answer,setAnswer]=useState(""); const choices = role === "ARCHIVE" ? [["ADRIAN_VALE","suspect.adrian"],["OWEN_PIKE","suspect.owen"],["NAOMI_BROOKS","suspect.naomi"],["ELI_REED","suspect.eli"]] : [["GUEST_ELEVATOR","stage.9.guest"],["WINDOW","stage.9.window"],["MAINTENANCE_PASSAGE","stage.9.passage"],["NEVER_LEFT","stage.9.never"]]; return <div className="final-deduction"><p className="kicker">{t("stage.9.title")}</p><h1>{role === "ARCHIVE" ? t("stage.9.archiveQ") : t("stage.9.fieldQ")}</h1><div className="deduction-choices">{choices.map(([value,key])=><button key={value} className={answer===value?"selected":""} onClick={()=>setAnswer(value)}>{t(key as never)}</button>)}</div><button className="button button-primary full" disabled={!answer || waiting} onClick={()=>send({type:"FINAL_ANSWER",value:answer})}>{waiting?t("stage.9.locking"):t("game.lock")}</button></div>; }

function Ending({ state }: { state: PublicRoomState }) { const { t } = useI18n(); const elapsed = state.startedAt && state.completedAt ? Math.max(0,state.completedAt-state.startedAt):0; const minutes=String(Math.floor(elapsed/60000)).padStart(2,"0"); const seconds=String(Math.floor(elapsed/1000)%60).padStart(2,"0"); const team=state.players.map(p=>p.displayName).join(" + "); const share=async()=>{ const text=`ROOM 404 — CASE SOLVED\n${team}\n${minutes}:${seconds}`; if(navigator.share) await navigator.share({title:"ROOM 404 — CASE SOLVED",text}); else await navigator.clipboard.writeText(text); }; return <div className="ending"><div className="ending-signal"><span>INCOMING MESSAGE · MAYA REED</span><p>“{t("ending.m1")}<br/>{t("ending.m2")}<br/><strong>{t("ending.m3")}</strong>”</p></div><div className="result-card"><p className="kicker">{t("ending.kicker")}</p><h1>ROOM 404</h1><h2>{t("ending.closed")}</h2><dl><div><dt>{t("ending.team")}</dt><dd>{team}</dd></div><div><dt>{t("ending.time")}</dt><dd>{minutes}:{seconds}</dd></div><div><dt>{t("ending.evidence")}</dt><dd>{state.optionalEvidence?"9/9":"8/9"}</dd></div><div><dt>{t("ending.rank")}</dt><dd>{t("ending.detective")}</dd></div></dl></div><div className="result-actions"><button className="button button-primary" onClick={share}>{t("ending.share")}</button><a className="button button-ghost" href="/play">{t("ending.challenge")}</a></div></div>; }

export function GameExperience({ state, send, error }: Props) {
  const { t } = useI18n(); const role = state.role!; const partner = state.players.find((player) => player.id !== state.me);
  const scene = useMemo(() => { if (state.stage === 1) return <StageOne role={role} send={send}/>; if (state.stage === 2) return <StageTwo role={role} send={send}/>; if (state.stage === 3) return <Paywall code={state.code} refresh={() => window.location.reload()}/>; if (state.stage === 4) return <StageFour role={role} send={send} waiting={state.waitingForPartner}/>; if (state.stage === 5) return <StageFive role={role} send={send}/>; if (state.stage === 6) return <StageSix role={role} send={send}/>; if (state.stage === 7) return <StageSeven role={role} send={send}/>; if (state.stage === 8) return <StageEight role={role} state={state} send={send}/>; if (state.stage === 9) return <StageNine role={role} waiting={state.waitingForPartner} send={send}/>; return <Ending state={state}/>; }, [role, send, state]);
  return <div className={`game-shell role-${role.toLowerCase()}`}><header className="game-header"><a className="game-mark" href="/">Ⅱ<span>ROOM 404</span></a><div className="sync-status"><i/>{t("game.sync")}</div><LanguageSwitcher/></header><div className="progress-line"><span style={{width:`${state.progress}%`}}/></div><aside className="game-meta"><div><small>{t("game.packet")}</small><strong>{role}</strong></div><div><small>{t("game.partner")}</small><strong>{partner?.displayName ?? "—"}</strong><i className={partner?.connected?"online":""}/></div><div><small>{t("game.progress")}</small><strong>{state.progress}%</strong></div></aside><main className="game-main">{scene}{error&&<div className="toast-error">{t("game.wrong")}</div>}</main><footer className="game-footer"><span>{t("game.attempts")}: {state.attempts}</span><span>{state.code}</span></footer></div>;
}
