import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { LanguageSwitcher } from "../components/LanguageSwitcher";
import { Mark } from "../components/Shell";
import { useI18n } from "../i18n";
import { api } from "../lib/api";

type Tab="overview"|"cases"|"rooms"|"assets";
interface DashboardData{metrics:{totalRooms:number;activeRooms:number;completedCases:number;purchases:number;averageCompletionMs:number};funnel:Record<string,number>}
interface CaseRow{id:string;title:string;slug:string;active:number;price_cents:number;current_version:number}
interface RoomRow{code:string;status:string;progress:number;player_count:number;created_at:number}
interface AssetRow{id:string;filename:string;mime_type:string;size_bytes:number;key:string}

export function Admin(){const{t}=useI18n();const navigate=useNavigate();const[tab,setTab]=useState<Tab>("overview");const[dashboard,setDashboard]=useState<DashboardData|null>(null);const[cases,setCases]=useState<CaseRow[]>([]);const[rooms,setRooms]=useState<RoomRow[]>([]);const[assets,setAssets]=useState<AssetRow[]>([]);const[loading,setLoading]=useState(true);const[creatingTest,setCreatingTest]=useState(false);
const load=useCallback(async()=>{setLoading(true);try{const me=await api("/api/admin/me");void me;if(tab==="overview")setDashboard(await api("/api/admin/dashboard"));if(tab==="cases")setCases((await api<{cases:CaseRow[]}>("/api/admin/cases")).cases);if(tab==="rooms")setRooms((await api<{rooms:RoomRow[]}>("/api/admin/rooms")).rooms);if(tab==="assets")setAssets((await api<{assets:AssetRow[]}>("/api/admin/assets")).assets);}catch{navigate("/admin/login");}finally{setLoading(false);}},[navigate,tab]);useEffect(()=>{void load();},[load]);
const logout=async()=>{await api("/api/admin/logout",{method:"POST"});navigate("/admin/login");};
const createTestRoom=async()=>{setCreatingTest(true);try{const data=await api<{state:{code:string}}>("/api/admin/test-room",{method:"POST"});navigate(`/play/${data.state.code}`);}finally{setCreatingTest(false);}};
return <div className="admin-page"><aside><Mark/><p className="admin-role">OWNER · UNLIMITED</p><nav>{(["overview","cases","rooms","assets"] as Tab[]).map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}><span>{item==="overview"?"⌁":item==="cases"?"▤":item==="rooms"?"◫":"◇"}</span>{t(`admin.${item}` as never)}</button>)}</nav><button className="logout" onClick={logout}>{t("admin.logout")} ↗</button></aside><main><header><div><p className="kicker">ROOM 404 · OPERATIONS</p><h1>{t(`admin.${tab}` as never)}</h1></div><LanguageSwitcher/></header>{loading?<div className="admin-loading">SYNCING ARCHIVE…</div>:<>
{tab==="overview"&&dashboard&&<><div className="metric-grid"><Metric label={t("admin.totalRooms")} value={dashboard.metrics.totalRooms}/><Metric label={t("admin.activeRooms")} value={dashboard.metrics.activeRooms}/><Metric label={t("admin.completed")} value={dashboard.metrics.completedCases}/><Metric label={t("admin.purchases")} value={dashboard.metrics.purchases}/></div><section className="admin-panel"><h2>{t("admin.funnel")}</h2><div className="funnel">{["landing_view","room_created","partner_joined","demo_completed","checkout_started","checkout_completed","case_completed"].map((event,index)=><div key={event}><span>0{index+1}</span><b>{event.replaceAll("_"," ")}</b><strong>{dashboard.funnel[event]??0}</strong></div>)}</div></section></>}
{tab==="cases"&&<section className="admin-panel"><table><thead><tr><th>Case</th><th>{t("admin.status")}</th><th>Price</th><th>Version</th><th/></tr></thead><tbody>{cases.map(item=><tr key={item.id}><td><b>{item.title}</b><small>{item.slug}</small></td><td><span className={`status ${item.active?"live":""}`}>{item.active?"PUBLISHED":"DRAFT"}</span></td><td>${(item.price_cents/100).toFixed(2)}</td><td>v{item.current_version}</td><td><button onClick={async()=>{await api(`/api/admin/cases/${item.id}`,{method:"PATCH",body:JSON.stringify({active:!item.active})});void load();}}>{item.active?"UNPUBLISH":"PUBLISH"}</button></td></tr>)}</tbody></table></section>}
{tab==="rooms"&&<section className="admin-panel"><div className="admin-toolbar"><div><h2>{t("admin.testRoom")}</h2><p>{t("admin.testRoomNote")}</p></div><button className="button button-primary" disabled={creatingTest} onClick={createTestRoom}>{creatingTest?"…":t("admin.testRoom")}</button></div><table><thead><tr><th>Room</th><th>{t("admin.status")}</th><th>{t("admin.players")}</th><th>{t("admin.progress")}</th><th/></tr></thead><tbody>{rooms.length?rooms.map(item=><tr key={item.code}><td><b>{item.code}</b><small>{new Date(item.created_at).toLocaleString()}</small></td><td><span className="status live">{item.status}</span></td><td>{item.player_count}/2</td><td>{item.progress}%</td><td><button onClick={async()=>{if(confirm(`Reset room ${item.code}?`)){await api(`/api/admin/rooms/${item.code}/reset`,{method:"POST"});void load();}}}>{t("admin.reset")}</button></td></tr>):<tr><td colSpan={5}>{t("admin.noData")}</td></tr>}</tbody></table></section>}
{tab==="assets"&&<section className="admin-panel"><form className="asset-upload" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);await api("/api/admin/assets",{method:"POST",body:form});event.currentTarget.reset();void load();}}><input type="file" name="file" accept="image/png,image/jpeg,image/webp,audio/wav,audio/mpeg,audio/ogg" required/><button className="button button-primary">{t("admin.upload")}</button></form><div className="asset-list">{assets.length?assets.map(item=><div key={item.id}><span>◇</span><p><b>{item.filename}</b><small>{item.mime_type} · {(item.size_bytes/1024).toFixed(1)} KB</small></p><button onClick={async()=>{if(confirm(`Delete ${item.filename}?`)){await api(`/api/admin/assets/${item.id}`,{method:"DELETE"});void load();}}}>DELETE</button></div>):<p>{t("admin.noData")}</p>}</div></section>}
</>}</main></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><strong>{value.toLocaleString()}</strong><i>LIVE</i></div>}
