import { puzzleSchema, type GameAction, type PlayerRole } from '../../shared/game';
import { local, type EvidenceFile } from '../../shared/investigation';

// This catalog is Worker-only. Send only earned files for the authenticated role.
type PrivateFile = EvidenceFile & { role: PlayerRole };
const files: PrivateFile[] = [];
function file(stage: number, role: PlayerRole, id: string, title: string, ptTitle: string, en: string, pt: string, extra: Partial<EvidenceFile> = {}) {
  files.push({ stage, role, id, title: local(title, ptTitle), body: local(en, pt), ...extra });
}
file(1,'ARCHIVE','card-eye','EYE / 8','OLHO / 8','Card recovered from the floor. Turn it over.','Cartão recuperado do chão. Examine o verso.',{symbol:'◉',digit:'8',back:local('The eye and the moon were never adjacent.','O olho e a lua nunca ficavam lado a lado.')});
file(1,'ARCHIVE','card-bell','BELL / 5','SINO / 5','No annotation on the reverse.','Sem anotação no verso.',{symbol:'♢',digit:'5'});
file(1,'ARCHIVE','card-moon','MOON / 2','LUA / 2','No annotation on the reverse.','Sem anotação no verso.',{symbol:'☾',digit:'2'});
file(1,'ARCHIVE','card-key','KEY / 7','CHAVE / 7','No annotation on the reverse.','Sem anotação no verso.',{symbol:'⚿',digit:'7'});
file(1,'ARCHIVE','cards-fragment','THE FOUR CARDS','OS QUATRO CARTÕES','Scheduled message / Maya Reed: If you opened both packets, I missed our meeting. Security reported me missing at 23:50. Recover my backup before trusting that story.\nI stored the cards loose, not in reading order. The key was immediately to the right of the moon. One card has a pencil mark on its back. Reconstruct the row, left to right; send the digits to FIELD.','Mensagem agendada / Maya Reed: Se abriram os dois pacotes, eu não cheguei ao encontro. A segurança registrou meu desaparecimento às 23:50. Recuperem meu backup antes de acreditar nessa versão.\nGuardei os cartões soltos, fora da ordem de leitura. A chave estava imediatamente à direita da lua. Um cartão tem uma marca a lápis no verso. Reconstruam a fileira da esquerda para a direita; enviem os dígitos ao CAMPO.');
file(1,'FIELD','photo-row',"MAYA'S NOTE",'BILHETE DE MAYA','Contact sheet, read left to right. The surviving edges show the BELL immediately to the left of the EYE. Neither pair of cards is numbered by position. ARCHIVE has the missing fragment and the backs. What row satisfies ALL observations?','Folha de contato, leitura da esquerda para a direita. As bordas preservadas mostram o SINO imediatamente à esquerda do OLHO. Nenhum par está numerado por posição. ARQUIVO tem o fragmento e os versos. Qual fileira respeita TODAS as observações?',{kind:'photo',asset:'/evidence/room-404-door.webp'});

file(2,'ARCHIVE','recorder-calibration',"MAYA'S FIELD NOTES",'ANOTAÇÕES DE MAYA','The recovered fragments belong to four independent recorder heads. Their display clocks drifted. Convert each displayed time to hotel time, then assemble the message chronologically. Each pulse becomes one count; a silent fragment counts too.\nHEAD K: display is 4 minutes fast.\nHEAD R: display is 2 minutes slow.\nHEAD M: accurate.\nHEAD T: display is 1 minute fast.\nThe completed message opens the backup that security tried to bury.','Os fragmentos pertencem a quatro gravadores independentes. Os relógios divergiram. Converta cada horário exibido para o horário do hotel e monte a mensagem cronologicamente. Cada pulso vale uma unidade; um fragmento silencioso também conta.\nCABEÇA K: visor 4 minutos adiantado.\nCABEÇA R: visor 2 minutos atrasado.\nCABEÇA M: correto.\nCABEÇA T: visor 1 minuto adiantado.\nA mensagem completa abre o backup que a segurança tentou esconder.');
for (const [id,time,pulses] of [['M','00:08',3],['T','00:11',1],['K','00:08',2],['R','00:04',0]] as const) {
  file(2,'FIELD',`clip-${id}`,`REC_001 / ${id}`,`REC_001 / ${id}`,`Recorder ${id} · display ${time}\nTranscript: ${pulses ? Array(pulses).fill('PULSE').join(' · ') : '[intact silent interval]'}\nAll four fragments are intact. Matching display times do not imply matching hotel times.`,`Gravador ${id} · visor ${time}\nTranscrição: ${pulses ? Array(pulses).fill('PULSO').join(' · ') : '[intervalo silencioso íntegro]'}\nOs quatro fragmentos estão íntegros. Horários de visor iguais não significam horários reais iguais.`,{kind:'audio',pulses});
}
file(3,'ARCHIVE','backup-index','BACKUP RECOVERED','BACKUP RECUPERADO','The recording unlocked an independent backup. Its hotel clock is certified: Maya entered Room 404 at 00:04, fourteen minutes AFTER security reported her disappearance. FIELD received a surviving doorway frame. Someone falsified the timeline.','A gravação abriu um backup independente. Seu relógio é certificado: Maya entrou no Quarto 404 às 00:04, quatorze minutos DEPOIS do desaparecimento registrado pela segurança. CAMPO recebeu um frame preservado da porta. Alguém falsificou a cronologia.');
file(3,'FIELD','backup-frame','SURVIVING FRAME / 00:06','FRAME PRESERVADO / 00:06','Backup frame, certified hotel time: an unidentified figure crosses the threshold of 404 at 00:06. The face is outside the frame. ARCHIVE recovered Maya’s entry time. Compare the two: she was not the last person through that door.','Frame do backup, horário certificado: uma figura não identificada cruza a porta do 404 às 00:06. O rosto está fora do enquadramento. ARQUIVO recuperou o horário da entrada de Maya. Comparem: ela não foi a última pessoa a passar pela porta.',{kind:'photo',asset:'/evidence/room-404-door.webp'});
file(4,'ARCHIVE','access-log','ACCESS LOG / UNCORRECTED','ACESSOS / SEM CORREÇÃO','Security backup recovered: Maya entered 404 AFTER the reported disappearance. Someone kept the original.\n23:58 · badge P · camera console\n00:14 · badge A · front desk\n23:41 · badge P · security office\n00:11 · badge N · service lift\nController audit: all badge readers display 20 minutes ahead of hotel time. A swipe proves the badge location, not automatically its owner.','Backup recuperado: Maya entrou no 404 DEPOIS do desaparecimento registrado. Alguém preservou o original.\n23:58 · crachá P · console de câmeras\n00:14 · crachá A · recepção\n23:41 · crachá P · segurança\n00:11 · crachá N · elevador de serviço\nAuditoria: todos os leitores exibem 20 minutos a mais que o horário do hotel. Uma leitura prova onde estava o crachá, não necessariamente seu dono.');
file(4,'FIELD','statements','STATEMENTS & CUSTODY','DEPOIMENTOS E CUSTÓDIA','All testimony uses HOTEL TIME.\nNaomi: I left at 23:45. Signed loan: badge N was with Eli from 23:40 to 00:20.\nOwen: I left at 23:30 and never returned. Badge P remained on my wrist; camera confirms no handoff.\nAdrian: I stayed at the front desk until midnight. Badge A never left me.\nEli: I used the service lift at 23:51 with the borrowed badge.\nIdentify the claim that cannot coexist with the corrected log.','Todos os depoimentos usam o HORÁRIO DO HOTEL.\nNaomi: Saí às 23:45. Empréstimo assinado: o crachá N ficou com Eli de 23:40 a 00:20.\nOwen: Saí às 23:30 e não voltei. O crachá P permaneceu no meu pulso; a câmera confirma que não houve troca.\nAdrian: Fiquei na recepção até meia-noite. O crachá A ficou comigo.\nEli: Usei o elevador de serviço às 23:51 com o crachá emprestado.\nIdentifiquem a afirmação incompatível com os registros corrigidos.');
file(5,'ARCHIVE','packets','RECOVERED PACKET HEADERS','CABEÇALHOS RECUPERADOS','A forged warning says: DO NOT TRUST FIELD. Authenticate the headers instead.\nPacket 2 · seal OPEN · previous 14 · current 15\nPacket 4 · seal CLOSED · previous 18 · current 19\nPacket 8 · seal CLOSED · previous 22 · current 24\nOne packet carries Maya’s intact camera index. FIELD must select its number.','Um aviso forjado diz: NÃO CONFIE NO CAMPO. Autentiquem os cabeçalhos.\nPacote 2 · selo ABERTO · anterior 14 · atual 15\nPacote 4 · selo FECHADO · anterior 18 · atual 19\nPacote 8 · selo FECHADO · anterior 22 · atual 24\nUm pacote contém o índice íntegro das câmeras de Maya. CAMPO deve selecionar seu número.');
file(5,'FIELD','integrity','PACKET INTEGRITY WARNING','ALERTA DE INTEGRIDADE','Maya’s offline verification card: an authentic packet has BOTH a CLOSED seal and a counter exactly one greater than its previous counter. The sender name and instructions are not proof of origin. ARCHIVE has the headers; request the surviving packet number.','Cartão de verificação offline de Maya: um pacote autêntico tem selo FECHADO E contador exatamente uma unidade acima do anterior. Nome do remetente e instruções não provam a origem. ARQUIVO tem os cabeçalhos; peça o número do pacote que resiste à verificação.');
file(6,'ARCHIVE','camera-audit','CCTV CLOCK AUDIT','AUDITORIA DOS RELÓGIOS','Index restored. Reconstruct Maya’s route using HOTEL TIME, not frame order.\nStairwell: display 6 minutes fast.\nGuest hall: display accurate.\nMaintenance door: display 8 minutes fast.\nService corridor: display 3 minutes slow.\nThe guest exit camera shows no crossing. Compare the four selected frames with FIELD.','Índice restaurado. Reconstruam a rota de Maya pelo HORÁRIO DO HOTEL, não pela ordem dos frames.\nEscadaria: visor 6 minutos adiantado.\nCorredor de hóspedes: visor correto.\nPorta de manutenção: visor 8 minutos adiantado.\nCorredor de serviço: visor 3 minutos atrasado.\nA câmera da saída de hóspedes não registra passagem. Comparem os quatro frames com CAMPO.');
for (const [id,en,pt,time] of [['C2','Stairwell','Escadaria','00:20'],['C4','Maintenance door','Porta de manutenção','00:25'],['C3','Guest hall','Corredor de hóspedes','00:04'],['C1','Service corridor','Corredor de serviço','00:08']]) {
  file(6,'FIELD',id,`${id} / ${en}`,`${id} / ${pt}`,`Display ${time}. Location: ${en}. Maya’s coat is visible. This frame alone does not establish its place in the sequence.`,`Visor ${time}. Local: ${pt}. O casaco de Maya está visível. Este frame isolado não determina sua posição na sequência.`,{kind:'photo',asset:'/evidence/cctv-fourth-floor.webp'});
}
file(7,'ARCHIVE','call-header','INCOMING CALL','CHAMADA RECEBIDA','Caller claims to be Maya: “Answer and I will show you the guest exit.”\nNegotiation header: challenge 31 · response 30 · relay GREEN.\nFIELD recovered her authentication convention. Decide whether to accept the identity. A rejected call is preserved as a transcript.','A pessoa diz ser Maya: “Atenda e eu mostro a saída de hóspedes.”\nCabeçalho: desafio 31 · resposta 30 · retransmissor VERDE.\nCAMPO recuperou a convenção de autenticação dela. Decidam se aceitam a identidade. Uma chamada recusada fica preservada como transcrição.');
file(7,'FIELD','call-protocol','MAYA’S CALL CONVENTION','CONVENÇÃO DE CHAMADA DE MAYA','Recovered with the camera index. Maya’s relay is GREEN; its response must be the challenge PLUS one. A matching relay alone is not sufficient. If either check fails, decline: the connection would expose the backup. Ask ARCHIVE for the actual header.','Recuperado com o índice. O retransmissor de Maya é VERDE; a resposta precisa ser o desafio MAIS um. Só o retransmissor correto não basta. Se qualquer verificação falhar, recusem: a conexão exporia o backup. Peça o cabeçalho real ao ARQUIVO.');
file(8,'ARCHIVE','work-orders','WORK ORDERS','ORDENS DE SERVIÇO','The caller tried to divert you to a monitored exit. Inspect the actual panel with FIELD.\nOrder 528 · copper latch · square seal · false wall\nOrder 417 · brass latch · split-circle seal · false wall\nOrder 631 · brass latch · square seal · guest lift\nThe optional override is the THREE-DIGIT order number matching both hardware features. A match opens the sealed repair note.','A chamada tentou desviar vocês para uma saída vigiada. Inspecionem o painel real com CAMPO.\nOrdem 528 · trava de cobre · selo quadrado · parede falsa\nOrdem 417 · trava de latão · selo de círculo partido · parede falsa\nOrdem 631 · trava de latão · selo quadrado · elevador de hóspedes\nO código opcional é o número de TRÊS DÍGITOS da ordem que corresponde às duas características. A combinação abre a nota de reparo lacrada.');
file(8,'FIELD','panel-photo','PANEL / INSPECTION','PAINEL / INSPEÇÃO','Visible inspection marks: BRASS latch, SPLIT-CIRCLE seal.\nFresh coat fibres on the inner edge match Maya’s CCTV coat. The duct beyond the panel connects to the service stairwell. Window seals are intact; the guest lift was locked from 23:50 to 00:30. These observations will matter in your final deduction.','Marcas visíveis: trava de LATÃO, selo de CÍRCULO PARTIDO.\nFibras recentes na borda interna combinam com o casaco de Maya no CCTV. O duto atrás do painel liga à escada de serviço. Lacres das janelas intactos; elevador de hóspedes travado das 23:50 às 00:30. Essas observações serão necessárias na dedução final.',{kind:'photo',asset:'/evidence/maintenance-passage.webp'});
file(9,'ARCHIVE','erase-log','CONSOLE TRANSACTIONS','TRANSAÇÕES DO CONSOLE','Restored transactions use HOTEL TIME. Badge access alone cannot prove who erased anything.\nTX-17 · 23:38 · token S7 · ERASE camera originals\nTX-21 · 23:39 · token S2 · EXPORT backup\nTX-24 · 23:42 · token S9 · READ directory\nFIELD recovered personal token custody. Name the eraser AND cite the transaction that proves the act. Also explain to FIELD which repair order matches their panel.','Transações restauradas usam o HORÁRIO DO HOTEL. Acesso por crachá sozinho não prova quem apagou arquivos.\nTX-17 · 23:38 · token S7 · APAGAR originais das câmeras\nTX-21 · 23:39 · token S2 · EXPORTAR backup\nTX-24 · 23:42 · token S9 · LER diretório\nCAMPO recuperou a custódia dos tokens pessoais. Identifique o autor E cite a transação que prova o ato. Explique ao CAMPO qual ordem corresponde ao painel.');
file(9,'FIELD','token-custody','PERSONAL TOKEN CUSTODY','CUSTÓDIA DOS TOKENS','Biometric tokens cannot be lent.\nS2: Naomi Brooks\nS9: Adrian Vale\nS7: Owen Pike\nEli Reed: no console token.\nARCHIVE has the transactions. Help distinguish deletion from preservation. For your own conclusion, select Maya’s exit AND cite the repair order compatible with the panel you inspected. Reopen the inspection and ask ARCHIVE for the work orders.','Tokens biométricos não podem ser emprestados.\nS2: Naomi Brooks\nS9: Adrian Vale\nS7: Owen Pike\nEli Reed: sem token de console.\nARQUIVO tem as transações. Ajude a distinguir exclusão de preservação. Na sua conclusão, selecione a saída de Maya E cite a ordem compatível com o painel inspecionado. Reabra a inspeção e peça as ordens ao ARQUIVO.');

const hints = {
  1: local('Treat the two adjacent pairs as blocks. Which arrangement also respects the note on the back?', 'Trate os dois pares adjacentes como blocos. Qual disposição também respeita a anotação no verso?'),
  2: local('A fast clock must be moved backwards. Correct each head separately before counting in chronological order.', 'Um relógio adiantado deve voltar. Corrija cada gravador separadamente antes de contar na ordem cronológica.'),
  4: local('Correct the readers first, then check who actually held each badge. A loan can explain an apparent contradiction.', 'Corrija os leitores e verifique quem realmente portava cada crachá. Um empréstimo pode explicar uma aparente contradição.'),
  5: local('Test both seal and counter on each header; passing only one test is not authentication.', 'Teste selo e contador em cada cabeçalho; passar em apenas um teste não autentica o pacote.'),
  6: local('Camera identifiers are not timestamps. Pair each location with its clock correction and sort the corrected times.', 'Identificadores de câmera não são horários. Relacione cada local à sua correção e ordene os horários corrigidos.'),
  7: local('Compare the response with the challenge using the convention. A familiar relay can still carry an impostor.', 'Compare a resposta ao desafio usando a convenção. Um retransmissor familiar ainda pode carregar um impostor.'),
  8: local('One hardware feature leaves two candidates. Match the latch AND the seal before taking the order number.', 'Uma característica deixa dois candidatos. Combine trava E selo antes de usar o número da ordem.'),
  9: local('Presence is not guilt: pair an operation with personal custody. For the exit, connect the physical panel to its repair record.', 'Presença não prova culpa: relacione uma operação à custódia pessoal. Para a saída, ligue o painel físico à sua ordem de reparo.'),
};
export const investigationPuzzles = Object.entries(hints).map(([stage,hint]) => puzzleSchema.parse({id:`investigation-${stage}`,stage:Number(stage),nodeType:'document_evidence',hint}));
export function evidenceFor(role: PlayerRole | null, stage: number, optional = false): EvidenceFile[] {
  const earned = files.filter(f => f.role === role && f.stage <= stage).map(({role: _role,...f}) => { void _role; return f; });
  if (optional && stage >= 8) earned.push({id:'repair-note',stage:8,title:local('SEALED REPAIR NOTE','NOTA DE REPARO LACRADA'),body:local('Maya: Naomi exported my backup before the originals vanished. The panel latch closes behind you without a key. That is how the room stayed locked.','Maya: Naomi exportou meu backup antes de os originais sumirem. A trava do painel fecha atrás de você sem chave. Foi assim que o quarto permaneceu trancado.')});
  return earned;
}
export const hintFor = (stage: number) => investigationPuzzles.find(p => p.stage === stage)?.hint;
export const initialCardOrder = ['card-eye','card-bell','card-moon','card-key'];
export function revisedCorrect(stage: number, role: PlayerRole | null, action: GameAction) {
  if (stage === 1) return role === 'FIELD' && action.type === 'SUBMIT_CODE' && action.value === '2758';
  if (stage === 2) return role === 'ARCHIVE' && action.type === 'SUBMIT_CODE' && action.value === '2031';
  if (stage === 5) return role === 'FIELD' && action.type === 'CONFIRM_DIGIT' && action.value === '4';
  if (stage === 6) return role === 'FIELD' && action.type === 'TRACE_PATH' && Array.isArray(action.value) && action.value.join('|') === 'C3|C1|C2|C4';
  if (stage === 7) return role === 'ARCHIVE' && action.type === 'CALL_DECISION' && action.value === 'DECLINED';
  if (stage === 9 && action.type === 'FINAL_ANSWER' && Array.isArray(action.value)) {
    return action.value.join('|') === (role === 'ARCHIVE' ? 'OWEN_PIKE|TX-17' : role === 'FIELD' ? 'MAINTENANCE_PASSAGE|417' : '');
  }
  return false;
}
